### ISSUE TITLE
Added custom rule messages won't show up

### ISSUE THREAD

**Issue by grrnikos** [alexgarrett/violin#1]
I add a couple of custom messages with `$v->addRuleMessage()` or `$v->addRuleMessages()` but it still outputs the original error messages even though the `ruleMessages` array gets updated.

**Comment by alexgarrett** [comment]
Can you show me your whole code?

**Comment by grrnikos** [comment]
```php
<?php

require 'vendor/autoload.php';

$v = new Violin\Violin;

// Input to validate
$input = [
    'name' => 'Nikos',
    'age' => 'hey'
];

// Validation rules
$rules = [
    'name' => 'required|alpha',
    'age' => 'required|int'
];

$v->validate($input, $rules);

// Custom rule messages
$v->addRuleMessage('required', 'You better fill in the %s field, or else I kill you.');
$v->addRuleMessage('age', 'Only numbers for age please.');

if($v->valid()) {
    echo 'Valid!';
} else {
    dd($v->errors());
}
```

**Comment by alexgarrett** [comment]
You need to call `addRuleMessage` or similar before you validate.

This has made me realise it should be flexible enough for you to define the rule messages anywhere, so I'll look into making the possible this week.

**Comment by grrnikos** [comment]
It does not work for me even if I call `addRuleMessage` before `validate`. Did you try it and it works?

**Comment by grrnikos** [comment]
Found something: it works but only for the first rule message (required), that in my case is valid. The second rule message is not updating.

**Comment by grrnikos** [comment]
LOL, it's a typo, I wrote `age` instead of `int`. I am sorry for this and thank you for helping me out

**Comment by alexgarrett** [comment]
No worries at all, thanks for filing an issue. I've added a todo for the flexibility and improvement of handling error messages anyway. Any other problems let me know.
