### ISSUE TITLE
Change in validate method

### ISSUE THREAD

**Issue by oxyzero** [alexgarrett/violin#29]
I want to discuss and hear opinions on the validate method.

Currently, we send data and define rules like this: 
```php
$v->validate([
    'username' => 'oxy',
    'age'      => 20,
    'password' => 'secret'
], [
    'username' => 'required',
    'age'      => 'required|int',
    'password' => 'required|alpha'
]);
```

My alternative is something like:
```php
$v->validate([
    'username' => [ 'oxy', 'required' ],
    'age'      => [ 20, 'required|int' ],
    'password' => [ 'secret', 'required|alpha' ]
]);
```

What do you think?

**Comment by alexgarrett** [comment]
I like this idea actually. The more I've been using Violin in projects the more I've found it to be annoying that I have to keep repeating the field names.                                                                                                                                                                                                                From: Renato MachadoSent: Sunday, 29 March 2015 23:27To: alexgarrett/violinReply To: alexgarrett/violinSubject: [violin] Change in validate method (#29)I wanted to discuss and hear opinions on the validate method.

Currently, we send data and define rules like this: 

$v->validate([
    'username' => 'oxy',
    'age'      => 20,
    'password' => 'secret'
], [
    'username' => 'required',
    'age'      => 'required|int',
    'password' => 'required|alpha'
]);

My alternative is something like:

$v->validate([
    'username' => [ 'oxy', 'required' ],
    'age'      => [ 20, 'required|int' ],
    'password' => [ 'secret', 'required|alpha' ]
]);

What do you think?

—Reply to this email directly or view it on GitHub.

**Comment by alexgarrett** [comment]
Merged.
