### ISSUE TITLE
Min rule bypass

### ISSUE THREAD

**Issue by Francismori7** [alexgarrett/violin#35]
Hi,

https://github.com/alexgarrett/violin/blob/master/src/Rules/MinRule.php#L11

Someone who needs an username with min(3) could actually just write "3" in the input box, and it would pass. We need to be able to specify if it should be a string or not, because right now it checks the value and if the value is a number, it checks if it is over or equal to the minimum. However, someone who writes "ha" would not pass, because then it checks against the string length.

We need better safety on there.

**Comment by alexgarrett** [comment]
Fixed in #41
