### ISSUE TITLE
Class 'Violin\violin' not found 

### ISSUE THREAD

**Issue by thanush** [alexgarrett/violin#46]
violin working fine on local server but it's showing error like below on live server
Fatal error: Class 'Violin\violin' not found in /var/www/html/start.php on line 8. i'm using digiatalocean

**Comment by tleb** [comment]
Not sure your issue is explicit enough, some code + `composer.json` maybe?

**Comment by oxyzero** [comment]
Check if your composer.json is correct, and also remember to install all of the dependencies needed on your server using composer. (don't use the require-dev as they are not necessary for production)

**Comment by thanush** [comment]
my composer.json file like this
{
	"require":{
		"alexgarrett/violin": "2.1.*"
	}
}
and php version 5.5.9-1ubuntu4.7


and my code is


<?php
use Violin\violin;

require 'vendor/autoload.php';

$v = new Violin;

$v->validate([
	'username' => ['sanzu', 'required|min(3)|max(20)'],
	'email'	   => ['sanzu@iamsanzu.com', 'required|email'],
	'password' => ['password123', 'required'],
	'password_conform'=> ['password123', 'required|matches(password)']
]);


if ($v->passes()) {
	echo "passed";
}else{
 var_dump($v->errors()->all());

}
but still getting error like this 

Fatal error: Class 'Violin\violin' not found in /var/www/html/vio/index.php on line 6
please help me 

it's working fine on local server but not in live sever.

**Comment by tleb** [comment]
I suppose that you either copied the vendor folder + composer.lock or that you did a `composer dumpautoload`?

**Comment by alexgarrett** [comment]
Have you run `composer install` on your server?

**Comment by tleb** [comment]
`composer install`, yes, my bad.

**Comment by pedzed** [comment]
> composer install, yes, my bad.

You should close this issue if it's fixed.

**Comment by tleb** [comment]
> You should close this issue if it's fixed.

I am not the one asking the question. :smile:

**Comment by thanush** [comment]
@alexgarrett  yes did but still same error...!

**Comment by pedzed** [comment]
>>> `composer install`, yes, my bad.

>> You should close this issue if it's fixed.

> I am not the one asking the question.

Sorry, didn't notice.

@thanush Try uppercasing the "V" in "violin":
```php
use Violin\Violin;
```

**Comment by thanush** [comment]
@pedzed  now it's saying

Fatal error: Class 'violin\violin' not found in /var/www/html/vio/index.php on line 6

**Comment by pedzed** [comment]
> @pedzed now it's saying
> 
> Fatal error: Class 'violin\violin' not found in /var/www/html/vio/index.php on line 6

Are you sure you didn't lowercase it? The "V" must be a capital letter.

```php
use Violin\Violin;
```

**Comment by thanush** [comment]
@pedzed  thank you buddy and thank you everybody especially @alexgarrett  it's working with 
use Violin\Violin;

**Comment by pedzed** [comment]
@thanush Could you close this issue if it's solved?
