### ISSUE TITLE
Some novice error when using the class

### ISSUE THREAD

**Issue by vladvisinescu** [alexgarrett/violin#55]
I`m getting a "Fatal error: Class 'Violin\Rules\Rule' not found" error after form submit. 
This is my code: 

```php
use Violin\Violin;

require 'vendor/autoload.php';

$v = new Violin;

$v->validate( [
	'title'       => [ $inputTitle, 'required' ],
	'location'    => [ $inputLocation, 'required' ],
	'email'       => [ $inputEmail, 'required|email' ],
	'phone'       => [ $inputPhone, 'required|int' ],
	'description' => [ $inputDescription, 'required|' ]
] );

if ( $v->passes() ) { 
        //do something
}
```

Note: I`m using the first part in a functions.php file in Wordpress and the validate + "passes" parts in a custom template.

Am I missing something ?

**Comment by alexgarrett** [comment]
Have you just copied the Violin.php file over to your server to use it?You'll need to install it with Composer.                                                                                                                                                                                                                From: vladvisinescuSent: Sunday, 24 May 2015 00:02To: alexgarrett/violinReply To: alexgarrett/violinSubject: [violin] Some novice error when using the class (#55)I`m getting a "Fatal error: Class 'Violin\Rules\Rule' not found" error after form submit. 
This is my code: 

use Violin\Violin;

require 'vendor/autoload.php';

$v = new Violin;

$v->validate( [
    'title'       => [ $inputTitle, 'required' ],
    'location'    => [ $inputLocation, 'required' ],
    'email'       => [ $inputEmail, 'required|email' ],
    'phone'       => [ $inputPhone, 'required|int' ],
    'description' => [ $inputDescription, 'required|' ]
] );

if ( $v->passes() ) { 
        //do something
}

Note: I`m using the first part in a functions.php file in Wordpress and the validate + "passes" parts in a custom template.

Am I missing something ?

—Reply to this email directly or view it on GitHub.

**Comment by oxyzero** [comment]
Change:
```php
'description' => [ $inputDescription, 'required|' ]
```
into:
```php
'description' => [ $inputDescription, 'required' ]
```

The problem was Violin was trying to figure out the rule class name for the '' string (after the | character).

**Comment by vladvisinescu** [comment]
so yeah, missed a pipe symbol.. thanks !
