### ISSUE TITLE
Any way to use on live server (not production) ?

### ISSUE THREAD

**Issue by vladvisinescu** [alexgarrett/violin#56]
...and without access to "composer install"... any chance ?

now all it does is breaking the page rendering whenever it encounters anything related to Violin.

**Comment by julianrichen** [comment]
You can always download the master branch, upload it to your server and use your own autoloader:
https://github.com/alexgarrett/violin/archive/master.zip

```php
// Your autoloader

use Violin\Violin;

$v = new Violin;

// Other Violin code
```

**Comment by vladvisinescu** [comment]
ok, that solved it! I thought there was also another "cleaner" way...
Thanks !

**Comment by tleb** [comment]
You can also do the composer install on your machine and upload the folder to the server by any way you want (ftp, upload of .zip to some service then download back on the server with curl/wget, etc).

**Comment by vladvisinescu** [comment]
yeah, well tried that and it didn`t work. nothing worked actually through the "vendor/autoload.php" method. @julianrichen `s solution was right for me, though I`m still wondering why the default method threw so many errors. (other packages included).
(sorry for bad English btw).

**Comment by tleb** [comment]
What errors did you get?

His solution works, but is not adapted as soon as you have a few dependencies and a complex architecture.

**Comment by pedzed** [comment]
You can this basic autoloader if you wish:

```php
spl_autoload_register(function($class) {
    $dirs = [
        dirname(__DIR__).'/classes/',
        dirname(__DIR__).'/vendor/',
    ];
    
    foreach($dirs as $dir) {
        $file = str_replace('\\', '/', rtrim($dir, '/').'/'.$class.'.php');
        
        if(is_readable($file)) {
            require_once($file);
            break;
        }
    }
});
```
I shouldn't have to explain what this does or how to make this work, but just in case:
- Whenever you call a class, it calls `spl_autoload_register`.
- `$dirs` is the directories the classes are stored in. Folders should match namespaces.
Say I want to write my own class `User` in the `pedzed\auth` namespace, I'd put it in `/classes/pedzed/auth/User.php`. (Case sensitive on Linux)
- For every directory in the `$dirs` array, it will try to find and load a class if readable. When a class is found, the file will be loaded and `break;` makes it stop looking further.

You might have to change `dirname(__DIR__)` to `__DIR__` or something else depending on where you will save this file. I usually put it in `/inc/init.php`.

**Comment by tleb** [comment]
I don't think the solution is using another autoloader. The Composer's one works really well, and is more adapted to complex projects, the problem is probably really easily solvable.

**Comment by vladvisinescu** [comment]
@tleb 
the error I was getting before implementing the manual require were like " Fatal Error: Class not found" etc. And you`re right, I guess. Composer`s autoloader should work, but it fails in some ocassions. Had the exact same problem with another project and ended up creating an autoloader myself (on a production site). What bothers me is that all works fine locally, but not live.

I`ll use @pedzed `s solution but on my next project. I`m too in a rush right now to be changing code again.

**Comment by tleb** [comment]
I don't think it was Composer which didn't do its job correctly, if you see what I mean.
