### ISSUE TITLE
AlphaDash not working.

### ISSUE THREAD

**Issue by RubenVermeulen** [alexgarrett/violin#67]
I'm trying to use 'alphaDash' but it's not working.

This is the code I'm using:

````
$v->validate([
        'name|Naam' => [$name, 'required|alphaDash']
]);
````

**Comment by tleb** [comment]
> it's not working

That's a really explicit error message. :)

**Comment by RubenVermeulen** [comment]
Haha, didn't notice I forgot to mention.

Fatal error: Class 'Violin\Rules\AlphaDashRule'

**Comment by pedzed** [comment]
That's because `AlphaDash` doesn't exist. It is a mistake in the README.

Reference: https://github.com/alexgarrett/violin/tree/master/src/Rules

**Comment by alexgarrett** [comment]
I'll update the readme, sorry for the confusion!
