### ISSUE TITLE
alnumDash Rule

### ISSUE THREAD

**Issue by rnottinger** [alexgarrett/violin#70]
I'm using alnumDash to validate username field...

$v = $app->validation;
$v->validate([
        'username' => [
            $username, 'required|alnumDash|max(20)|uniqueUsername'
    ]
]);

When I enter richard in the username field... in chrome browser on desktop computer...validation passes and I do not get a error message...which is to be expected

BUT when I enter richard in the username field...in safari on iphone 6+...the validation for alnumDash fails and I get the error message "username must be alphanumeric with dashes and underscores permitted."

Below I added a custom field Message for the alnumDash rule to replace the default validation error message... to confirm the value that is being tested. 
Whenever the validation error message is displayed I get the message --> richard

$this->addFieldMessages([
            'username' => [
                'uniqueUsername' => 'That username is already in use.',
                'alnumDash' => '{value}'
            ]
        ]);

So my issue is the validation rule alnumDash does not work as expected on the Iphone 6+ safari browser.

Thank you,

**Comment by pedzed** [comment]
Please, [format your code](https://help.github.com/articles/github-flavored-markdown/) next time so it's better readable.

I really doubt that it's because of safari on iOS, because PHP is server side code. It gets executed on the server, and not, unlike JavaScript, in the client (the browser).

**Comment by rnottinger** [comment]
thanks pedzed

disregard... its working now

I refreshed the safari browser several times and turned off/on the iphone and validation is working as expected.
