### ISSUE TITLE
json format

### ISSUE THREAD

**Issue by lalocespedes** [alexgarrett/violin#73]
How can i get errors array in json format?
i tried
$errors = (array)$v->errors();
echo json_encode($errors);

but i have this result

{"\u0000*\u0000messages":{"email_address":["email_address must be a valid email address."]}}

what are? \u0000*\u0000 characters?
thnks in advance

**Comment by oxyzero** [comment]
The reason this is happening is because you're actually encoding the MessageBag object (returned from the errors() method).

If you want to format your errors from the 'email_address' into json you can do:

```php
$errors = $v->errors()->get('email_address');
echo json_encode($errors);
```

You can also use the `first(field)` and `all()` methods.

**Comment by lalocespedes** [comment]
i've done with all and first methods, but i want, the filed and messages into array..

the all() method only give me  the message, but i want the filed too.

**Comment by oxyzero** [comment]
Unfortunately the MessageBag doesn't support parsing it's data to JSON format.

However, you can achieve what you want with the following script:

```php
$errors = $v->errors();

$json_array = [];

foreach ($errors->keys() as $key) {
    if ($errors->has($key)) {
        $json_array[$key] = $errors->get($key);
    }
}

echo json_encode($json_array);
```

**Comment by lalocespedes** [comment]
Wow men, its work like a charm, thks so much.
