### ISSUE TITLE
Custom Rule Problem

### ISSUE THREAD

**Issue by wlachenal** [alexgarrett/violin#75]
Hello,

I'm creating a custom rule for role which is `roleExists`. So it must be required, if it's filled up it will take to next step on by checking if role exists in the system.

    $v->validate([
        'role' => [$role, 'required|roleExists'],
    ]);

    $this->addRuleMessages([
        'roleExists' => 'Role does not exists, you sure you are not doing something fishy?'
    ]);

And on the rule itself. In the `if statement` on `validate_roleExists`. I have to check if it exists or not. So if it's exists it will echo true, on the other hand it will echo false.

    public function validate_roleExists($value, $input, $args) {

        if ((bool) $this->role->where('id', $value)->count() === true) {
            echo 'true';
            return true;
        } else {
            echo 'false';
            return false;
        }
    }

So the problem is, if role is `empty`, for some reason the rule `roleExists` is being triggered but it should not, is there any problem with this code?

    [10] => role is required.
    [11] => Role does not exists, you sure you are not doing something fishy?

-- Edit --
Well I found my workaround on this. 

    public function validate_roleExists($value, $input, $args) {

        if (!empty($value)) {
            return (bool) $this->role->where('id', $value)->count();
        }
        return true;
    }

Well obviously, it checks if the value is empty, if it is it will return true to prevent triggering an error that the role does not exists. So if it's not empty, here comes the main part, it will return true or false whether the role exists or not.

Any cleaner solution for this part?

**Comment by alexgarrett** [comment]
It's difficult, since there's a fine line between what should be validated (e.g. in your case it's more of an application level, rather than a data validation level).

You could always do:

```php
public function validate_roleExists($value, $input, $args) {
    if (empty($value)) {
        return false;
    }
    return (bool) $this->role->where('id', $value)->count();
}
```

Which means removing the required rule, but it's slightly cleaner.

Having typed that, I think your solution is better, although misleading to look at the code.
