### ISSUE TITLE
Traduction

### ISSUE THREAD

**Issue by T-Nagui** [alexgarrett/violin#81]
hi, i m asking if you thout about making Ini file for traduction of standard messages !!? 

sory for my english :dancers:

**Comment by alexgarrett** [comment]
Sorry, I'm really not sure what you mean. Did you mean translation?

**Comment by tleb** [comment]
I think he did, *traduction* is the french for *translation*. :)

I'm not sure a ini file is the best idea, because of parsing, etc.
@T-Nagui Aren't custom messages enough?

**Comment by T-Nagui** [comment]
hi (sory for my bad english),
yes i mean translation :) 
I'im using 3 lnguage in my web site (Frensh, English and arabic) for that i thout about ini file but if you have a sugestion tel me :)

**Comment by tleb** [comment]
Wouldn't this work?

```php
switch ($lang) {
    case 'fr':
        $violin->setCustomMessage('foo', 'bar');
        // french language
        break;
    case 'ar':
        // arabic language
        break;
    default:
        // default language
        break;
}
```

Of course, this would need to be adapted to your situation (get data from a configuration file, etc).

You could extend `Violon` to get the methods you want.

**Comment by alexgarrett** [comment]
@T-Nagui Thanks for making it clear!

@tleb I think it's just better to keep everything in one file.

```php
return [
    'required' => 'You better fill in the {field} field, or else.',
    'int' => 'The {field} needs to be an integer, but I found {value}.',
];
```

And then load it into Violin with a package like https://github.com/hassankhan/config or by requiring it in.

```php
// Very rough example, untested

$messages = require 'messages.xx.php'; // where xx is FR, EN, whatever.
$v->addRuleMessages($messages); // this is loading the returned array into Violin
```

Hope that makes sense. Let us know how you get on.

**Comment by T-Nagui** [comment]
thinks, yes very good idea @alexgarrett  i well do it :dancer: 
@tleb i it well try to mexid with config file of HassanKhan

again think both :D

**Comment by alexgarrett** [comment]
@T-Nagui You're more than welcome. Feel free to open another issue if you're stuck with it. Good luck!

**Comment by oxyzero** [comment]
Another possible way could be to add a argument, that could be passed on Violin's constructor.

```php
$v = new Violin\Violin('EN');
```

Or by passing an array in the constructor.
And on the rules class:

```php

class ExampleRule
{
    public function error()
    {
        return [
            'EN' => '{field} must be alphanumeric.',
            'FR' => '...',
        ];
    }
}
```

If any rule didn't had a translation, we would skip it and just give the raw error (like the ones we have now).
If the translation required didn't exist we default it to English.

But by any means a translation option for Violin sounds great :+1:

**Comment by pedzed** [comment]
> And then load it into Violin with a package like https://github.com/hassankhan/config or by requiring it in.

That's redundant, because PHP puts it automatically in a variable.

```php
// config/app.php
return [
    'name' => 'Violin',
];

// index.php

$appConfig = require('config/app.php');
var_dump($appConfig['name']);
```
