### ISSUE TITLE
Can not register new Rules

### ISSUE THREAD

**Issue by ComputerCandy** [alexgarrett/violin#92]
While I was folowing the PHP Authentication tutorial series I came along an error at part 13. THis is the error:
Slim Application Error
The application could not run because of the following error:

Details

Type: ErrorException
Code: 8
Message: Undefined index: uniqueEmail
File: C:\wamp64\www\website\vendor\alexgarrett\violin\src\Violin.php
Line: 224
Trace

#0 C:\wamp64\www\website\vendor\alexgarrett\violin\src\Violin.php(224): Slim\Slim::handleErrors(8, 'Undefined index...', 'C:\\wamp64\\www\\w...', 224, Array)
#1 C:\wamp64\www\website\vendor\alexgarrett\violin\src\Violin.php(138): Violin\Violin->fetchMessage('email', 'uniqueEmail')
#2 C:\wamp64\www\website\app\routes\auth\register.php(46): Violin\Violin->errors()
#3 [internal function]: {closure}()
#4 C:\wamp64\www\website\vendor\slim\slim\Slim\Route.php(468): call_user_func_array(Object(Closure), Array)
#5 C:\wamp64\www\website\vendor\slim\slim\Slim\Slim.php(1357): Slim\Route->dispatch()
#6 C:\wamp64\www\website\vendor\slim\slim\Slim\Middleware\Flash.php(85): Slim\Slim->call()
#7 C:\wamp64\www\website\vendor\slim\slim\Slim\Middleware\MethodOverride.php(92): Slim\Middleware\Flash->call()
#8 C:\wamp64\www\website\vendor\slim\slim\Slim\Middleware\PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#9 C:\wamp64\www\website\vendor\slim\slim\Slim\Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#10 C:\wamp64\www\website\public\index.php(5): Slim\Slim->run()
#11 {main}

My code is almost the same as the PHP Authentication tutorial but a few modificatons.
All my code: [website.zip](https://github.com/alexgarrett/violin/files/170650/website.zip)

This is all run with WAMP Server 3.0.0 on PHP 5.6.16

**Comment by pedzed** [comment]
You have better luck by asking here: https://www.codecourse.com/forum

**Comment by CeramicTitan** [comment]
|uniqueEmail isnt a valid rule, therefore it cannot parse it through.

**Comment by pedzed** [comment]
I didn't hear back from you. Is the issue solved?

**Comment by pedzed** [comment]
Please, close this issue.
